name: Rust CI Linux

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: hhanh00/warp
        submodules: true
        path: warp
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Tauri build
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.1-dev
        npm install
        npx tauri icon
        NO_STRIP=1 npx tauri build
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: zwl-recover.AppImage
        path: src-tauri/target/release/bundle/appimage/*.AppImage
    - name: Create Release
      if: startsWith(github.ref_name, 'v')
      uses: softprops/action-gh-release@v2
      with:
        files: src-tauri/target/release/bundle/appimage/*.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}