name: Rust CI Windows

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: hhanh00/warp
        submodules: true
        path: warp
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Tauri build
      run: |
        npm install
        npx tauri icon
        npx tauri build --bundles nsis
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zwl-recover-setup.exe
        path: src-tauri/target/release/bundle/nsis/*-setup.exe
    - name: Create Release
      if: startsWith(github.ref_name, 'v')
      uses: softprops/action-gh-release@v2
      with:
        files: src-tauri/target/release/bundle/nsis/*-setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}